#' The package {here} uses relative to the project root, so users should work
#' in an **R project**.
#' 
#' Note: For the purposes of a course, the users could simply make an R project
#' that is used for the entire course. This could be a folder which they
#' download on their own computer and create a project based on an existing
#' directory. It's easy!
#' 
#' Let's assume that you have a project set up to be the folder `here_tutorial`

#' Loading necessary packages
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load(here, ggplot2,
       install = TRUE, update = FALSE)

#' Import data using here()
dataset <- read.csv(here("data/dummy_data.csv"), header = TRUE)

#' Now, you're free to use the dataset however you want.
t.test(dataset$length, dataset$height)

testplot <- ggplot(data = dataset, aes(x = age, y = length, 
                                       color = group, shape = group)) +
  geom_point(size = 5, alpha = 0.5) + 
  ggtitle("Some example plot of totally meaningless data.") +
  theme_bw()

#' Since here() is just for finding files, you can export an item just as you'd
#' normally do so if you're already in a working directory (which you will be
#' if you have a project set up)
fname <- paste("output/", "testplot_01", ".png", sep = "")
ggsave(filename = fname,
       plot = testplot,
       width = 5.5,
       height = 3.5,
       units = "in",
       device = "png",
       dpi = "print")

#' This is just to clean up the files generated by the tutorial so the output
#' folder is empty for the next person!
if (file.exists(fname)) {
  file.remove(fname)
  cat(paste("File `", fname, "` successfully deleted.", sep = ""))
} else {
  message("No file found.\n Check to make sure output folder is clean.")
}
